# .codeclimate.yml

version: "2"

# --------------------------------------------------------------------------
# prepare: Actions to perform before analysis begins
#   fetch: Remote files to fetch (files placed relative to the repo's root dir)
#     url: url to fetch
#     path: destination relative to repo's root directory

# --------------------------------------------------------------------------
# checks: Configuration of maintainability checks
#   <name>
#     enabled: true|false
#     config: check configuration

# --------------------------------------------------------------------------
# plugins: Enable optional engines to run in addition to your analysis
#   <name>
#     enabled: true|false
#     channel: alternate channel to use (stable is default)
#     config: plugin configuration

plugins:
  markdownlint:
    enabled: true
    checks:
      # ... IGNORE INLINE HTML ...
      MD033:
        enabled: false
  shellcheck:
    enabled: true

# --------------------------------------------------------------------------
# exclude_patterns: Exclude files and/or directories from analysis
# - <pattern>
# - <pattern>

exclude_patterns:
- "docs/"
- "other/mathematics/"
- "other/random-things/williams-diner-pinball-machine-cheat-sheet/"
- "other/stem/"
- "software/development/languages/latex-cheat-sheet"
- "software/development/languages/go-cheat-sheet/src/"
- "software/development/languages/go-cheat-sheet/methods.md"
- "software/development/languages/go-cheat-sheet/functions.md"
- "other/science/physical-science/physics-cheat-sheet/*"
- "other/single-board-computers/raspberry-pi/specifications-cheat-sheet/README.md"
